"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _about_page from './about-page.bones.json'
import _home_page from './home-page.bones.json'
import _policy_page from './policy-page.bones.json'
import _protected_page from './protected-page.bones.json'
import _reset_password_page from './reset-password-page.bones.json'
import _return_policy_page from './return-policy-page.bones.json'
import _shop_page from './shop-page.bones.json'

registerBones({
  "about-page": _about_page,
  "home-page": _home_page,
  "policy-page": _policy_page,
  "protected-page": _protected_page,
  "reset-password-page": _reset_password_page,
  "return-policy-page": _return_policy_page,
  "shop-page": _shop_page,
})
